name: Deploy Website build to FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for the current branch

    - name: Deploy Website via Rsync to FTP
      uses: burnett01/rsync-deployments@7.0.2
      with:
        switches: -avzr --delete
        path: site/
        remote_host: ${{ secrets.FTP_GRILLE_SERVER }}
        remote_user: ${{ secrets.FTP_GRILLE_USERNAME }}
        remote_key: ${{ secrets.FTP_GRILLE_PASSWORD }}
        remote_path: /
        exclude: 'logs/ README.md'
